services:
  news_api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    ports:
      - "8080:8080"
    networks:
      - same_net
    environment:
      SPRING_DATASOURCE_URL: $POSTGRES_URL
      SPRING_DATASOURCE_USERNAME: $POSTGRES_USER
      SPRING_DATASOURCE_PASSWORD: $POSTGRES_PASSWORD
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_LIQUIBASE_ENABLED: false
    depends_on:
      - postgresql_db

  postgresql_db:
    image: postgres
    restart: no
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    networks:
      - same_net
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  same_net:

volumes:
  db_data: